{
 "title": "BlueIris",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "camera",
    "label": "Camera",
    "query": {
     "query": "label_values(gw_blue_iris_ai_duration, camera)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(gw_blue_iris_ai_duration, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DeepStack Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_ai_restarted[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Timeouts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_ai_timeout[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Server Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_ai_servererror[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Not Responding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_ai_notresponding[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_logerror_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(blueiris_exporter_errors)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AI Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blueiris_ai_count{camera=~\"$camera\", type=~\"$type\"}[$__range]) +1",
     "legendFormat": "{{camera}} - {{type}}"
    }
   ]
  },
  {
   "title": "Camera Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blueiris_camera_status", "legendFormat": "{{camera}}" }
   ]
  },
  {
   "title": "AI Analysis",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "blueiris_ai_duration_distinct{camera=~\"$camera\", type=~\"$type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Analysis",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (camera, type) (blueiris_ai_duration_distinct{camera=~\"$camera\", type=~\"$type\"})",
     "legendFormat": "{{camera}} - {{type}}"
    }
   ]
  },
  {
   "title": "Blue Iris AI Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (type, camera) (sum_over_time(blueiris_ai_duration_distinct{type=~\"$type\", camera=~\"$camera\"}[$__range])) / sum by (type, camera) (count_over_time(blueiris_ai_duration_distinct{type=~\"$type\", camera=~\"$camera\"}[$__range]))",
     "legendFormat": "{{camera}} - {{type}}"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "sum by (error) (blueiris_logerror{error!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}