{
 "title": "BlueIris Loki",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "camera",
    "label": "Camera",
    "query": {}
   },
   {
    "name": "type",
    "label": "Type",
    "query": {}
   },
   {
    "name": "object",
    "label": "Object",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\"} |= \"Started version\" | regexp `Started version (?P<version>[0-9.]+)`",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Update Check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\"} \r\n|~ \"Started version|now available\" \r\n| line_format \"{{if contains \\\"now available\\\" __line__}}UPDATE_AVAILABLE{{else}}UP_TO_DATE{{end}}\"",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Current Profile",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\"} |= \"Current profile\" | regexp `Current profile (?P<profile>.+)`",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\", level=\"error\"} [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Log Warnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\", level=\"warning\"} [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI has been restarted\" [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Starting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI: is being started|AI is being restarted\" [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI: has been started|AI has been started\" [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Timeouts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI: timeout\" [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Server Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI: error\" [$__range])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "AI Not Responding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"blue_iris\"} |~ \"AI: not responding\" [$__range])) or on() vector(0)"
    }
   ]
  },
  { "title": "AI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "AI Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(object, alert_type) (count_over_time({job=\"blue_iris\", duration!=\"\", object=~\"$camera\", ai_object=~\"$object\", alert_type=~\"$type\"} [$__auto]))",
     "legendFormat": "{{object}} - {{alert_type}}"
    }
   ]
  },
  {
   "title": "AI Analysis",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\", duration!=\"\", object=~\"$camera\", ai_object=~\"$object\", alert_type=~\"$type\"}"
    }
   ]
  },
  {
   "title": "AI Analysis",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (object, alert_type, ai_object) (last_over_time(\r\n  {job=\"blue_iris\", duration!=\"\", object=~\"$camera\", ai_object=~\"$object\", alert_type=~\"$type\"} \r\n  | unwrap duration [15s]\r\n))",
     "legendFormat": "{{object}} - {{alert_type}} - {{ai_object}}"
    }
   ]
  },
  {
   "title": "Blue Iris AI Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (object, alert_type, ai_object) (avg_over_time(\r\n  {job=\"blue_iris\", duration!=\"\", object=~\"$camera\", ai_object=~\"$object\", alert_type=~\"$type\"} \r\n  | unwrap duration [$__range]\r\n))",
     "legendFormat": "{{object}} - {{alert_type}} - {{ai_object}}"
    }
   ]
  },
  {
   "title": "Triggers & Pushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Triggers / Camera",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(object) (count_over_time({job=\"blue_iris\", object=~\"$camera\"} |~ \"Trigger:\" !~ \"Alert confirmed|Alert canceled\" [$__range]))",
       "legendFormat": "{{object}}"
      }
     ]
    },
    {
     "title": "Push Notifications",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(object) (count_over_time({job=\"blue_iris\", object=~\"$camera\"} |~ \"Push:\" [$__range])) or on() vector(0)"
      }
     ]
    },
    {
     "title": "Triggers / Camera",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(object) (count_over_time({job=\"blue_iris\", object=~\"$camera\"} |~ \"Trigger:\" !~ \"Alert confirmed|Alert canceled\" [5m]))",
       "legendFormat": "{{object}}"
      }
     ]
    },
    {
     "title": "Push Notifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(object) (count_over_time({job=\"blue_iris\", object=~\"$camera\"} |~ \"Push:\" [$__range])) or on() vector(0)",
       "legendFormat": "{{object}}"
      }
     ]
    }
   ]
  },
  { "title": "Folders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Folder Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (object) (last_over_time({job=\"blue_iris\", disk_pct!=\"\", disk_pct!~\"%.+\"} | unwrap disk_pct [$__range]))",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Folder Hours%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (object) (last_over_time({job=\"blue_iris\", hours_pct!=\"\", hours_pct!~\"%.+\"} | unwrap hours_pct [$__range]))",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Folder Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (object) (last_over_time({job=\"blue_iris\", disk_free!=\"\"} | unwrap disk_free [$__range]))",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "Log Errors & Warnings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Log Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (message) (\r\n  count_over_time(\r\n    {job=\"blue_iris\", level=\"error\"} | regexp \"(?P<message>.*)\" [$__range]\r\n  )\r\n) or on() vector(0)",
     "legendFormat": "{{message}}"
    },
    {
     "direction": "backward",
     "expr": "sum (\r\n  count_over_time(\r\n    {job=\"blue_iris\", level=\"error\"} [$__range]\r\n  )\r\n) or on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "Log Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (message) (\r\n  count_over_time(\r\n    {job=\"blue_iris\", level=\"warning\"} | regexp \"(?P<message>.*)\" [$__range]\r\n  )\r\n) or on() vector(0)",
     "legendFormat": "{{message}}"
    },
    {
     "direction": "backward",
     "expr": "sum (\r\n  count_over_time(\r\n    {job=\"blue_iris\", level=\"warning\"} [$__range]\r\n  )\r\n) or on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Log Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"blue_iris\", level=\"warning\"}"
    }
   ]
  }
 ]
}